// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define RIBBON_TAB_HOME 2000 
#define RIBBON_TAB_HOME_LabelTitle_RESID 50
#define RIBBON_TAB_WORLD_SETTINGS 20001 
#define RIBBON_TAB_WORLD_SETTINGS_LabelTitle_RESID 51
#define RIBBON_GROUP_USER_SEARCH 1002 
#define RIBBON_GROUP_USER_SEARCH_LabelTitle_RESID 101
#define RIBBON_GROUP_USER_GMP_ROTECT 1001 
#define RIBBON_GROUP_USER_GMP_ROTECT_LabelTitle_RESID 102
#define ButtonSearchUserByName 2 
#define ButtonSearchUserByName_LabelTitle_RESID 201
#define ButtonSearchUserByName_TooltipTitle_RESID 60001
#define ButtonSearchUserByName_TooltipDescription_RESID 60002
#define ButtonSearchUserByName_LargeImages_RESID 60003
#define ButtonSearchUserById 3 
#define ButtonSearchUserById_LabelTitle_RESID 202
#define ButtonSearchUserById_TooltipTitle_RESID 60004
#define ButtonSearchUserById_TooltipDescription_RESID 60005
#define ButtonSearchUserById_LargeImages_RESID 60006
#define ButtonGmProtect 4 
#define ButtonGmProtect_LabelTitle_RESID 203
#define ButtonGmProtect_TooltipTitle_RESID 60007
#define ButtonGmProtect_TooltipDescription_RESID 60008
#define ButtonGmProtect_LargeImages_RESID 60009
#define ButtonDropDownGallery 5 
#define ButtonDropDownGallery_LabelTitle_RESID 250
#define ButtonDropDownGallery_TooltipTitle_RESID 60010
#define ButtonDropDownGallery_TooltipDescription_RESID 60011
#define ButtonDropDownGallery_SmallImages_RESID 60012
#define BUTTON_CHECK_USER_INVIS_MODE 6 
#define BUTTON_CHECK_USER_INVIS_MODE_LabelTitle_RESID 251
#define BUTTON_CHECK_USER_MATCHLESS_MODE 7 
#define BUTTON_CHECK_USER_MATCHLESS_MODE_LabelTitle_RESID 252
#define BUTTON_CHECK_USER_ONEKILL_MODE 8 
#define BUTTON_CHECK_USER_ONEKILL_MODE_LabelTitle_RESID 253
#define BUTTON_CHECK_USER_NOTMOVE_MODE 9 
#define BUTTON_CHECK_USER_NOTMOVE_MODE_LabelTitle_RESID 254
#define BUTTON_CHECK_USER_SAYTALK_MODE 10 
#define BUTTON_CHECK_USER_SAYTALK_MODE_LabelTitle_RESID 255
#define BUTTON_CHECK_USER_MATCHLESS2_MODE 11 
#define BUTTON_CHECK_USER_MATCHLESS2_MODE_LabelTitle_RESID 256
#define BUTTON_CHECK_USER_NO_ATK_MODE 12 
#define BUTTON_CHECK_USER_NO_ATK_MODE_LabelTitle_RESID 257
#define BUTTON_CHECK_USER_COMMUNITY_MODE 13 
#define BUTTON_CHECK_USER_COMMUNITY_MODE_LabelTitle_RESID 258
#define BUTTON_CHECK_USER_TALK_MODE 14 
#define BUTTON_CHECK_USER_TALK_MODE_LabelTitle_RESID 259
#define BUTTON_CHECK_USER_SHOUTTALK_MODE 15 
#define BUTTON_CHECK_USER_SHOUTTALK_MODE_LabelTitle_RESID 260
#define BUTTON_CHECK_USER_FREEPK_MODE 16 
#define BUTTON_CHECK_USER_FREEPK_MODE_LabelTitle_RESID 261
#define BUTTON_CHECK_USER_MAILBOX_MODE 17 
#define BUTTON_CHECK_USER_MAILBOX_MODE_LabelTitle_RESID 262
#define BUTTON_CHECK_USER_OLDBOY_MODE 18 
#define BUTTON_CHECK_USER_OLDBOY_MODE_LabelTitle_RESID 263
#define BUTTON_CHECK_USER_DENIAL_MODE 19 
#define BUTTON_CHECK_USER_DENIAL_MODE_LabelTitle_RESID 264
#define BUTTON_CHECK_USER_EXP_STOP_MODE 20 
#define BUTTON_CHECK_USER_EXP_STOP_MODE_LabelTitle_RESID 265
#define BUTTON_CHECK_USER_DONTTALK_MODE 21 
#define BUTTON_CHECK_USER_DONTTALK_MODE_LabelTitle_RESID 266
#define BUTTON_CHECK_USER_OBSERVE_MODE 22 
#define BUTTON_CHECK_USER_OBSERVE_MODE_LabelTitle_RESID 267
#define ButtonCloseServer 23 
#define ButtonCloseServer_LabelTitle_RESID 300
#define ButtonCloseServer_LargeImages_RESID 60013
#define ButtonKickAllUsers 24 
#define ButtonKickAllUsers_LabelTitle_RESID 301
#define ButtonKickAllUsers_LargeImages_RESID 60014
#define ButtonDumpStats 25 
#define ButtonDumpStats_LabelTitle_RESID 302
#define ButtonDumpStats_LargeImages_RESID 60015
#define cmdApplicationMenu_LabelTitle_RESID 60016
#define GroupUserState_LabelTitle_RESID 60017
